### PR TITLE
Do file system check before resize (#1484575)

### PR DESCRIPTION
**Pull request by vpodzime**
Otherwise the resize usually fails.

### CODE REVIEW

**Comment by AdamWill** [comment]
I am unsure if the last change - going back from `-n` to `-p` - belongs in this commit, per the discussion when it was changed from `-p` to `-n` in a43dc757eff7fe9417f72e25fc373d09439963de . It *may* be appropriate to change this back now, but shouldn't it be a separate PR where we can discuss and check for sure that it won't lead to unexpected access to filesystems the user didn't want us to touch?

**Comment by vpodzime** [comment]
> shouldn't it be a separate PR where we can discuss and check for sure that it won't lead to unexpected access to filesystems the user didn't want us to touch?

I think it's okay to discuss it here. *ext* resize doesn't really work without the change so it's either all or nothing. Regarding the access to file systems, ``do_check()`` is only called in the ``_pre_resize()`` and ``_post_resize()`` hooks now so only when users explicitly say they want a file system to be resized. Which should be fine, I think. In the long term it might make sense to split things into two methods ``do_check()`` and ``do_repair()`` similarly how [*libblockdev* has these things separated](http://storaged.org/libblockdev/libblockdev-FS.html#bd-fs-repair).

**Comment by AdamWill** [comment]
so, is this gonna be merged?

**Comment by vpodzime** [comment]
> so, is this gonna be merged?

I think we should wait for @dwlehman's opinion on this.

**Pull request merged**
