### PR TITLE
blivet: Enable the extended node bitmap for F2FS

### PR DESCRIPTION
**Pull request by ZVNexus**
* With the default I was running out of inodes, disk reported no additional space after only using about 20%.

### CODE REVIEW

**Comment by StorageGhoul** [comment]
Can one of the admins verify this patch?

**Comment by ZVNexus** [comment]
@vojtechtrefny As the original author for F2FS support in blivet can you take a look?

**Comment by vojtechtrefny** [comment]
Jenkins, ok to test.

**Review by vojtechtrefny — APPROVED** [review]
Looks good to me, thank you.

**Pull request merged**
