### PR TITLE
Added support for device tags

### PR DESCRIPTION
**Pull request by japokorn**
added tags support for ks parameter 'ignoredisk'
added tests for 'ignoredisk' tags
added tags support for ks parameter 'clearpart'
added tests for 'clearpart' tags

### CODE REVIEW

**Comment by japokorn** [comment]
Partial PR. Will be updated.

**Comment by vpodzime** [comment]
There are PEP8 check failures in the CI results.

**Comment by japokorn** [comment]
PEP8 fixed.

**Comment by japokorn** [comment]
pushed

**Pull request merged**
