### PR TITLE
Weblate l10n migration

### PR DESCRIPTION
**Pull request by vojtechtrefny**
PO files are now in a [separate repository](https://github.com/storaged-project/blivet-weblate) managed by weblate. This PR adds the repository as a submodule to blivet with `make po-pull` updating the submodule.
I've removed the POT file update from the bumpver target. Updating it before making a release is too late -- we should give translators some time to translate new strings. I plan to create a simple script that will run from our Jenkins to update the POT file regularly.

### CODE REVIEW

**Comment by vojtechtrefny** [comment]
Jenkins, test this please.

**Comment by vojtechtrefny** [comment]
Jenkins, test this please.

**Comment by vojtechtrefny** [comment]
This should be now ready for review. I was waiting with this because Anaconda team was planning to create some automation for the POT file update process, but they ended up doing this manually so I've used their solution for now. I still plan to add a Jenkins job or something similar to update the blivet-weblate repository automatically, but this has to wait for now.

There definitely will be some issues with the release process but we can't be sure without actually merging this and doing a new release.

Using a separate repository brings some issues and I'm not 100 % sure using the submodule is the best approach, but it's definitely better than having Weblate mess with our repository. I don't have a separate repository for blivet-gui and I've already had a PR with [20+ commits for one language](https://github.com/storaged-project/blivet-gui/pull/166) and daily emails from Weblate complaining about not being able to merge changes from upstream repository...

**Comment by vojtechtrefny** [comment]
Zanata is scheduled to be removed during Fedora 33 development cycle: https://fedoraproject.org/wiki/Changes/Zanata_removal

**Comment by jkonecny12** [comment]
Thanks for info. I'll migrate rest of our translations soon.

**Pull request merged**
