### PR TITLE
initial PowerNV class support

### PR DESCRIPTION
**Pull request by sharkcz**

### CODE REVIEW

**Comment by dwlehman** [comment]
Hmm, I wonder if this should wait until 3.2.0 or even 4.0.0 since we would suddenly be reclassifying this hardware and handling it differently.

**Comment by sharkcz** [comment]
I want to make the change in F-31, so whatever version of blivet will be there.

**Comment by vojtechtrefny** [comment]
Jenkins, ok to test.

**Comment by sharkcz** [comment]
Hi, what's the plan for merging this? The anaconda part got merged today.

**Comment by vojtechtrefny** [comment]
> Hi, what's the plan for merging this? The anaconda part got merged today.

We(with @jkonecny12) did a new build together for rawhide with this as a downstream patch in blivet. I need to discuss this with @dwlehman and decide about the new version before merging this.

**Comment by sharkcz** [comment]
OK, no objections about the interim solution from my side, thanks.

**Pull request merged**
