### PR TITLE
Add support for creating shared LVM setups

### PR DESCRIPTION
**Pull request by vojtechtrefny**
This feature is requested by GFS2 for the storage role. This adds support for creating shared VGs and activating LVs in shared mode.

### CODE REVIEW

**Review by japokorn — DISMISSED** [review]
Looks good to me.

**Comment by japokorn** [comment]
When creating the first shared VG (and using `sanlock` lock manager) `vgcreate` has to be given non-PV device otherwise VG creation will fail. This functionality does not seem to be handled. (When testing the thing I got the error message described in ref.)

Ref: [lvmlockd(8)](https://man7.org/linux/man-pages/man8/lvmlockd.8.html) 'Creating the first sanlock VG'.

**Comment by vojtechtrefny** [comment]
> When creating the first shared VG (and using `sanlock` lock manager) `vgcreate` has to be given non-PV device otherwise VG creation will fail. This functionality does not seem to be handled. (When testing the thing I got the error message described in ref.)
> 
> Ref: [lvmlockd(8)](https://man7.org/linux/man-pages/man8/lvmlockd.8.html) 'Creating the first sanlock VG'.

I added two more commits that should address this -- we don't really need to run `pvcreate` first, so we can just skip it for all shared VGs. I really hope this doesn't mean that **only** the first created VG must be created this way. There might be some more caveats so I am moving this to draft, let me know if the fix works.

**Review by japokorn — APPROVED** [review]
LGTM
I managed to test shared VG creation using storage role and ha_cluster system role.
I think this PR can be merged.

**Pull request merged**
