### PR TITLE
Remove the Blivet.roots attribute

### PR DESCRIPTION
**Pull request by poncovka**
Remove some leftover code that manipulates with collected installation roots.
These objects are part of Anaconda.

**Depends on:** https://github.com/rhinstaller/anaconda/pull/4271

### CODE REVIEW

**Comment by StorageGhoul** [comment]
Can one of the admins verify this patch?

**Comment by vojtechtrefny** [comment]
Jenkins, ok to test.

**Review by vojtechtrefny — APPROVED** [review]

**Comment by vojtechtrefny** [comment]
@poncovka so the Anaconda PR is now merged, can we merge this now? Do you need this in some specific version of Fedora? This will go into 3.6 which we don't plan to build for F37.

**Comment by poncovka** [comment]
> @poncovka so the Anaconda PR is now merged, can we merge this now? Do you need this in some specific version of Fedora? This will go into 3.6 which we don't plan to build for F37.

@vojtechtrefny, yes this PR can be merged and released in F38 (Rawhide). We don't want it in F37.

**Pull request merged**
