### PR TITLE
Make sure that LUKS.has_key always returns a boolean value

### PR DESCRIPTION
**Pull request by vojtechtrefny**
We don't want to return 'None' here.

Related: https://github.com/rhinstaller/anaconda/pull/4873

### CODE REVIEW

**Review by poncovka — COMMENTED** [review]
Thanks! Btw. I think there are three different definitions of `has_key` that look like this.

**Review by jkonecny12 — APPROVED** [review]
Thanks for the fix.

**Comment by vojtechtrefny** [comment]
> Thanks! Btw. I think there are three different definitions of `has_key` that look like this.

Oh, I forgot about Stratis. Fixed, thanks.

**Review by japokorn — APPROVED** [review]
Looks good to me.

**Pull request merged**
