### PR TITLE
Added support for device tags

### PR DESCRIPTION
**Pull request by japokorn**
added tags support for ks parameter 'partition'
added tests for 'partition' tags

### CODE REVIEW

**Comment by japokorn** [comment]
jenkins, test this please

**Comment by dwlehman** [comment]
Jenkins, test this please.

**Comment by vojtechtrefny** [comment]
If I understand this correctly this a feature for anaconda? Is there some tracking issue for the anaconda part?
I think this also needs some better explanation in the commit message -- function called `expand_taglist` doesn't look like something that adds support for device tags.

**Comment by japokorn** [comment]
Currently discussing this PR with anaconda team.

**Comment by vojtechtrefny** [comment]
Any update on this?

**Comment by vojtechtrefny** [comment]
> Any update on this?

Same question :-)

I think we can merge this now and possibly add more changes later. Thoughts @dwlehman @japokorn ?

**Comment by japokorn** [comment]
I see no harm in merging this.
It only adds new functionality which is never used at this moment.
Most of the tags support is already in blivet for quite some time anyways.

**Pull request merged**
