### PR TITLE
Make use of the new info provided for LVs

### PR DESCRIPTION
**Pull request by vpodzime**
To speed things up by not doing extra calls to libblockdev and to make things more reliable by using better source of information.

### CODE REVIEW

**Comment by dwlehman** [comment]
Looks good to me aside from the `pylint` and `pep8` failures.

**Comment by vpodzime** [comment]
> Looks good to me aside from the pylint and pep8 failures.

Resolved.

**Comment by vojtechtrefny** [comment]
Looks good to me too.

**Comment by vpodzime** [comment]
The second patch here needs to be held off for now (until LVM team fixes the issues with roles being reported for pools). PR #472 contains just the first function from here.

**Comment by dwlehman** [comment]
@vpodzime what is the status of the postponed patch from this? Has it been merged?

**Comment by vpodzime** [comment]
> @vpodzime what is the status of the postponed patch from this? Has it been merged?

The [LVM bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1346323) is still untouched.

**Comment by vojtechtrefny** [comment]
The LVM bug was closed as WONTFIX so I'm closing this too.

**Pull request closed without merging**
