### PR TITLE
Rhel7 branch nvdimm devices handling in installer mode

### PR DESCRIPTION
**Pull request by rvykydal**
Depends on https://github.com/storaged-project/blivet/pull/694

### CODE REVIEW

**Comment by vojtechtrefny** [comment]
Jenkins, ok to test.

**Comment by rvykydal** [comment]
@vojtechtrefny: I've added one fixup revealed in testing on real HW.

**Comment by vojtechtrefny** [comment]
Jenkins, test this please.

**Comment by vojtechtrefny** [comment]
Jenkins, test this please.

**Pull request merged**
